// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "7a406a04-8a74-445a-b775-2bf31b4f8fc2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573034872);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7222);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573034842);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6e38fbc2-538e-4fc0-842c-4c5adf05ac05}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1573034850939");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1573038450939");
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1573034848");
user_pref("browser.slowStartup.averageTime", 4359);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191031085722");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1573034844);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1573034847102");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "25fa36add73d4dd29ba99531486bf6a0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"05e91a72-783c-4f20-948e-fec38e6cd08b\",\"screenshots@mozilla.org\":\"e65f3297-6ef2-474c-b517-f70972256f64\",\"webcompat-reporter@mozilla.org\":\"536f0914-91a2-4bd2-8fb5-f5bab2a20312\",\"webcompat@mozilla.org\":\"42f4fc77-47ab-47a5-a99a-b390e155497e\",\"default-theme@mozilla.org\":\"8668e65e-00c9-4606-bcfc-dc9cd3f88fa4\",\"google@search.mozilla.org\":\"469a8f1f-fe38-4477-b8df-5e1f72845856\",\"amazondotcom@search.mozilla.org\":\"37dcc0e1-7e36-4037-a4cb-61d504e43a08\",\"bing@search.mozilla.org\":\"024b59ec-e568-4cda-992e-98bb9820e95f\",\"ddg@search.mozilla.org\":\"7bfd9d04-8dec-464e-8ab5-bcd170bc1833\",\"ebay@search.mozilla.org\":\"77c0433e-5464-46b2-8a0b-c962aa8b944e\",\"twitter@search.mozilla.org\":\"fc9cbb19-fc0b-41a0-84be-8c79aa1e5537\",\"wikipedia@search.mozilla.org\":\"622ae758-c30e-4674-83c3-0b5b98f40590\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3d7adcf1-054b-435a-acf4-015d796fe08b");
user_pref("security.sandbox.plugin.tempDirSuffix", "2560fcd1-f953-4234-8cf0-a2ac76ee3b77");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1573034840);
user_pref("toolkit.telemetry.cachedClientID", "c1421432-cdc5-4b48-9783-75197be78b0d");
user_pref("toolkit.telemetry.previousBuildID", "20191031085722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
